version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/.env
    networks:
      - easyserve-network

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - easyserve-network
    depends_on:
      - backend

  admin:
    build: ./Admin
    container_name: admin
    ports:
      - "3001:80"
    networks:
      - easyserve-network
    depends_on:
      - backend

networks:
  easyserve-network:
    driver: bridge
